# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b013f02339cdf4744521bc78320fdb8b2273c7cf22a5f2985254439c0f6c2ffb11e297b15c344a7602131c6a2589d0cecb7dcfdbf48bd4e3a2617af8d3ed964

test:
  secret_key_base: eabc17f784a376c6fa46f40f19fb9967396dd0d61f7b77048e710e25c95dbf7912adc393a17fdce0d676ba6c36c979935bede0319d66adc8e7d4905365bb4682

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
